### ISSUE TITLE
Tunocent todo

### ISSUE THREAD

**Issue by MauPalantir** [acdh-oeaw/vicav-vue3#192]
- [x] Document the simple word search  boxesfor alif and ayn (?)
- [x] Document the wildcard word search mode 
- [x] Change the wildcard functionality to expect .* in "word autocomplete search" to be consistent with the other window
- [x] Add the special characters input box to Word autocomplete search input widgets  on corppus and feature/seamples earch form
- [x] Better documentation in the help text about the exact search
- [x] make sure the hilighted parts of the bibliography are rendered bold/italic --> the current raw data seems fine now  (with @rendition = "#i"), though doesn seem to be deployed
- [x] Add secondary speakers into the data table Speakers field (and change caption to Speakers)

**Comment by MauPalantir** [comment]
Add secondary speakers into the data table Speakers field (and change caption to Speakers)
